version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: night-routine
    main: ./cmd/night-routine
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64 # Keep only amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{ .Env.BUILD_DATE }} # Use env var passed from workflow

# Docker builds are now handled by GitHub Actions

# Use built-in Syft integration for SBOM generation
sboms:
  - artifacts: archive # Generate SBOM for the binary archive
    # GoReleaser defaults to CycloneDX JSON format, which is good.

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
  mode: replace
