version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: night-routine
    main: ./cmd/night-routine
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64 # Keep only amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dockers:
  - image_templates:
      - "ghcr.io/belphemur/night-routine:{{ .Version }}-amd64"
      - "ghcr.io/belphemur/night-routine:latest-amd64"
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--cache-from=type=gha,scope={{.Env.GITHUB_REF}}"
      - "--cache-to=type=gha,mode=max,scope={{.Env.GITHUB_REF}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=night-routine"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: amd64
    goos: linux
    extra_files:
      - configs/routine.toml

  - image_templates:
      - "ghcr.io/belphemur/night-routine:{{ .Version }}-arm64"
      - "ghcr.io/belphemur/night-routine:latest-arm64"
    use: buildx
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--cache-from=type=gha,scope={{.Env.GITHUB_REF}}"
      - "--cache-to=type=gha,mode=max,scope={{.Env.GITHUB_REF}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=night-routine"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64
    goos: linux
    extra_files:
      - configs/routine.toml

docker_manifests:
  - name_template: ghcr.io/belphemur/night-routine:{{ .Version }}
    image_templates:
      - ghcr.io/belphemur/night-routine:{{ .Version }}-amd64
      - ghcr.io/belphemur/night-routine:{{ .Version }}-arm64
  - name_template: ghcr.io/belphemur/night-routine:latest
    image_templates:
      - ghcr.io/belphemur/night-routine:latest-amd64
      - ghcr.io/belphemur/night-routine:latest-arm64

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

# signs our docker image
# https://goreleaser.com/customization/docker_sign
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+

# Use built-in Syft integration for SBOM generation
sboms:
  - artifacts: archive # Generate SBOM for the binary archive
    # GoReleaser defaults to CycloneDX JSON format, which is good.

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
  prerelease: auto
  mode: replace
